DROP DATABASE IF EXISTS eventaid_db;
CREATE DATABASE eventaid_db;
USE eventaid_db;

CREATE TABLE roles (
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name TEXT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password BINARY(60),
  role TINYINT UNSIGNED NOT NULL,
  FOREIGN KEY (role) REFERENCES roles(id),
  PRIMARY KEY (id)
);

# TODO